# Create Data

In [1]:
%%capture
%%bash
python ./generate_data.py
python ./run_ddl.py

Run Python code as shown below

In [2]:
a = 10

Run SQL code as shown below, with the `%%sql` called magics

In [3]:
%%sql
select 1

   1
0  1

We use the `prod.db` schema where all our tables are create by `run_ddl.py`

In [4]:
%%sql 
use prod_db

Empty DataFrame
Columns: []
Index: []

## Your code below

In [5]:
%%sql 
WITH orders_cte AS (
    SELECT
        o_orderkey,
        o_custkey,
        o_orderstatus,
        CAST(o_orderdate AS TIMESTAMP) AS o_orderdate,
        o_orderpriority,
        o_clerk,
        o_shippriority,
        o_comment,
        o_totalprice
    FROM orders
),
stg_customers AS (
    SELECT
        c_custkey,
        c_name,
        c_address,
        c_nationkey,
        c_phone,
        c_acctbal,
        c_mktsegment,
        c_comment
    FROM customer
),
nation_cte AS (
    SELECT
        CAST(n_nationkey AS INT) AS n_nationkey,
        CAST(n_name AS STRING) AS n_name,
        CAST(n_regionkey AS INT) AS n_regionkey,
        CAST(n_comment AS STRING) AS n_comment
    FROM nation
),
dim_customers AS (
    SELECT
        c.c_custkey,
        c.c_name,
        c.c_address,
        c.c_nationkey,
        n.n_name AS nation_name,
        c.c_phone,
        c.c_acctbal,
        c.c_mktsegment,
        c.c_comment
    FROM stg_customers c
    INNER JOIN nation_cte n ON c.c_nationkey = n.n_nationkey
)
SELECT
    o.o_orderkey,
    o.o_custkey,
    o.o_orderstatus,
    o.o_orderdate,
    o.o_orderpriority,
    o.o_clerk,
    o.o_shippriority,
    o.o_totalprice,
    c.c_name AS customer_name,
    c.c_address AS customer_address,
    c.c_phone AS customer_phone,
    c.c_acctbal AS customer_account_balance,
    c.c_mktsegment AS customer_market_segment,
    c.nation_name AS customer_nation_name
FROM orders_cte o
INNER JOIN dim_customers c ON o.o_custkey = c.c_custkey;

,o_orderkey,o_custkey,o_orderstatus,o_orderdate,o_orderpriority,o_clerk,o_shippriority,o_totalprice,customer_name,customer_address,customer_phone,customer_account_balance,customer_market_segment,customer_nation_name
0,897,4894,P,1995-03-20,1-URGENT,Clerk#000000316,0,66775.72,Customer#000004894,qccDi3BeqTSkIJKsp21j4KBsQpPk0Gt,30-152-685-8820,7927.44,HOUSEHOLD,SAUDI ARABIA
1,4034,9233,F,1993-11-14,4-NOT SPECIFIED,Clerk#000000548,0,307637.71,Customer#000009233,1Ba3hAO5jmBFJpKq2QIdZlb3Z,33-327-912-9200,4227.72,FURNITURE,UNITED KINGDOM
2,4769,12044,P,1995-04-14,4-NOT SPECIFIED,Clerk#000000116,0,206126.35,Customer#000012044,u9bevlA h3PS,10-488-427-2414,4825.26,MACHINERY,ALGERIA
3,5123,964,O,1998-02-10,1-URGENT,Clerk#000000776,0,18908.75,Customer#000000964,"2DpdvfAw4TuXl8DV,YVBwGsK7oLzkYr",22-974-772-2802,4756.58,FURNITURE,JAPAN
4,6695,1697,F,1992-06-28,5-LOW,Clerk#000000877,0,322140.76,Customer#000001697,8aHZSJIoZKtIfcD8IFMCu,34-288-313-5272,-913.24,FURNITURE,UNITED STATES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,370917,13240,O,1996-11-20,4-NOT SPECIFIED,Clerk#000000170,0,120765.87,Customer#000013240,"PJ,znldxQIQzPz1OUJ,A2edR37Sv9gpL1eJ3k",34-177-589-8705,5764.35,FURNITURE,UNITED STATES
996,370980,6424,O,1996-09-16,1-URGENT,Clerk#000000964,0,138463.90,Customer#000006424,JM18rGuDap8AhcSqcLsTFObP6 DF8,16-525-665-8732,258.29,MACHINERY,FRANCE
997,371043,6424,O,1995-04-30,5-LOW,Clerk#000000477,0,37138.82,Customer#000006424,JM18rGuDap8AhcSqcLsTFObP6 DF8,16-525-665-8732,258.29,MACHINERY,FRANCE
998,371559,5759,F,1992-03-13,4-NOT SPECIFIED,Clerk#000000609,0,54661.17,Customer#000005759,KH OTbvxFKOB40,24-556-307-7039,313.45,HOUSEHOLD,KENYA
999,371846,13240,P,1995-03-31,1-URGENT,Clerk#000000504,0,168100.26,Customer#000013240,"PJ,znldxQIQzPz1OUJ,A2edR37Sv9gpL1eJ3k",34-177-589-8705,5764.35,FURNITURE,UNITED STATES

In [6]:
%%sql
DESCRIBE part;

        col_name      data_type comment
0      p_partkey         bigint    None
1         p_name         string    None
2         p_mfgr         string    None
3        p_brand         string    None
4         p_type         string    None
5         p_size            int    None
6    p_container         string    None
7  p_retailprice  decimal(15,2)    None
8      p_comment         string    None

In [7]:
%%sql
DESCRIBE supplier;

      col_name      data_type comment
0    s_suppkey         bigint    None
1       s_name         string    None
2    s_address         string    None
3  s_nationkey         bigint    None
4      s_phone         string    None
5    s_acctbal  decimal(15,2)    None
6    s_comment         string    None

In [9]:
%%sql
DESCRIBE partsupp;

        col_name      data_type comment
0     ps_partkey         bigint    None
1     ps_suppkey         bigint    None
2    ps_availqty            int    None
3  ps_supplycost  decimal(15,2)    None
4     ps_comment         string    None

In [10]:
%%sql
DESCRIBE customer;

       col_name      data_type comment
0     c_custkey         bigint    None
1        c_name         string    None
2     c_address         string    None
3   c_nationkey         bigint    None
4       c_phone         string    None
5     c_acctbal  decimal(15,2)    None
6  c_mktsegment         string    None
7     c_comment         string    None

In [11]:
%%sql
DESCRIBE nation;

      col_name data_type comment
0  n_nationkey       int    None
1       n_name    string    None
2  n_regionkey       int    None
3    n_comment    string    None

In [12]:
%%sql
DESCRIBE lineitem;

           col_name      data_type comment
0        l_orderkey         bigint    None
1         l_partkey         bigint    None
2         l_suppkey         bigint    None
3      l_linenumber            int    None
4        l_quantity  decimal(15,2)    None
5   l_extendedprice  decimal(15,2)    None
6        l_discount  decimal(15,2)    None
7             l_tax  decimal(15,2)    None
8      l_returnflag         string    None
9      l_linestatus         string    None
10       l_shipdate           date    None
11     l_commitdate           date    None
12    l_receiptdate           date    None
13   l_shipinstruct         string    None
14       l_shipmode         string    None
15        l_comment         string    None

In [13]:
%%sql
DESCRIBE region;

      col_name data_type comment
0  r_regionkey       int    None
1       r_name    string    None
2    r_comment    string    None

In [14]:
%%sql
DESCRIBE orders;

          col_name      data_type comment
0       o_orderkey         bigint    None
1        o_custkey         bigint    None
2    o_orderstatus         string    None
3     o_totalprice  decimal(15,2)    None
4      o_orderdate           date    None
5  o_orderpriority         string    None
6          o_clerk         string    None
7   o_shippriority            int    None
8        o_comment         string    None

In [3]:
# List available databases
spark.sql("SHOW DATABASES").show()

+---------+
|namespace|
+---------+
|     prod|
|  prod_db|
+---------+

In [5]:
# List existing tables/views across all schemas
#spark.sql("SHOW TABLES").show()

# List tables in prod_db
spark.sql("SHOW TABLES IN prod_db").show()

# List tables in prod
spark.sql("SHOW TABLES IN prod").show()

+---------+---------+-----------+
|namespace|tableName|isTemporary|
+---------+---------+-----------+
|  prod_db|   orders|      false|
|  prod_db| partsupp|      false|
|  prod_db| supplier|      false|
|  prod_db| lineitem|      false|
|  prod_db|   nation|      false|
|  prod_db|     part|      false|
|  prod_db| customer|      false|
|  prod_db|   region|      false|
+---------+---------+-----------+

+---------+---------+-----------+
|namespace|tableName|isTemporary|
+---------+---------+-----------+
+---------+---------+-----------+

In [6]:
target_db = "prod_db"
tables = ["region", "nation", "part", "supplier", "partsupp", "customer", "orders", "lineitem"]

for table in tables:
    # Read table with explicit database qualification
    df = spark.table(f"{target_db}.{table}")
    
    # Export to local CSV
    df.coalesce(1).write \
        .mode("overwrite") \
        .option("header", "true") \
        .option("delimiter", ",") \
        .csv(f"./data_exports/{table}")
        
    print(f"Exported {table}")

Exported region
Exported nation

Exported part
Exported supplier

Exported partsupp

Exported customer

Exported orders

Exported lineitem